application: finalproject
version: 1
runtime: python27
api_version: 1
threadsafe: true

# [START handlers]
handlers:
- url: /css
  static_dir: css
- url: /templates
  static_dir: html_templates
  application_readable: true
- url: /.*
  static_files: index.html	
  upload: index\.html
  #script: finalproject.application
- url: /js
  static_dir: js
# [END handlers]

# [START libraries]
libraries:
- name: webapp2
  version: latest
- name: jinja2
  version: latest
# [END libraries]

